// these are hardcoded list of "meta" pages

const systemLinks = [
	// blank is homepage
	"",
	"scp-series-6",
	"scp-series-6-tales-edition",
	"scp-series-5",
	"scp-series-5-tales-edition",
	"scp-series-4",
	"scp-series-4-tales-edition",
	"scp-series-3",
	"scp-series-3-tales-edition",
	"scp-series-2",
	"scp-series-2-tales-edition",
	"scp-series",
	"scp-series-1-tales-edition",
	"foundation-tales",
	"series-archive",
	"incident-reports-eye-witness-interviews-and-personal-logs",
	"creepy-pasta",
	"user-curated-lists",
	"joke-scps",
	"joke-scps-tales-edition",
	"scp-ex",
	"explained-scps-tales-edition",
	"goi-formats",
	"audio-adaptations",
	"scp-artwork-hub",
	"contest-archive",
	"canon-hub",
	"groups-of-interest",
	"log-of-anomalous-items",
	"log-of-extranormal-events",
	"log-of-unexplained-locations",
	"about-the-scp-foundation",
	"object-classes",
	"personnel-and-character-dossier",
	"security-clearance-levels",
	"secure-facilities-locations",
	"task-forces",
	"guide-hub",
	"usertools",
	"tag-search",
	"meet-the-staff",
	"criticism-policy",
	"licensing-guide",
	"image-use-policy",
	"chat-guide",
	"deletions-guide",
	"seminars-hub",
	"donations-policy",
	"links",
	"guide-for-newbies",
	"how-to-write-an-scp",
	"faq",
	"site-rules",
	"scp-international",
	"top-rated-pages-this-month",
	"new-pages-feed",
	"random:random-scp",
	"random:random-tale",
	"system:recent-changes",
	"lowest-rated-pages",
	"contribute",
	"authors-pages",
	"news",
	"archived-news",
	"collaboration-contest",
	"featured-tale-archive",
	"featured-scp-archive-ii",
	"featured-goi-format-archive",
	"international-goi-contest-2019",
	"main",
	"contact-staff",
	"tales-by-title",
	"tales-by-author",
	"tales-by-date",
	"reviewers-spotlight-archive",
	"144-hour-jam-contest",
	"event-featured-archive",
	"licensing-master-list"
];

const systemPrefixes = [
	"featured-tale",
	"featured-scp",
	"featured-goi",
	"tales-by",
	"scp-series"
];

const metaTags = [
	'artwork',
	'author',
	'hub',
	'essay'
];

module.exports = {
	systemLinks,
	systemPrefixes,
	metaTags
};
